#!/bin/bash

cd "$(git rev-parse --show-toplevel)"

echo "Removing previous test output"
cd test
rm -rf output

echo "Simple spec"
#../bin/cli.js --spec-mode example-spec.js
../bin/cli.js react-element.coffee output/react-element.pdf
